# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: spectrum-analyzer 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "spectrum-analyzer"
  s.version = "0.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Roberts"]
  s.date = "2013-12-12"
  s.description = "Analyze a wav file for specific frequency signatures"
  s.email = "justin.roberts@careerbuilder.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/spectrum-analyzer.rb",
    "lib/spectrum-analyzer/config.rb",
    "lib/spectrum-analyzer/functions.rb",
    "lib/spectrum-analyzer/functions/analyze.rb",
    "lib/spectrum-analyzer/functions/generator.rb",
    "lib/spectrum-analyzer/functions/window_functions.rb",
    "lib/spectrum-analyzer/objects/analysis.rb",
    "lib/spectrum-analyzer/objects/domain.rb",
    "lib/spectrum-analyzer/objects/file.rb",
    "lib/spectrum-analyzer/objects/spectrum.rb",
    "spec/analyze.wav",
    "spec/spec_helper.rb",
    "spec/spectrum-analyzer_spec.rb",
    "spectrum-analyzer.gemspec"
  ]
  s.homepage = "http://github.com/jusroberts/spectrum-analyzer"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.11"
  s.summary = "Analyze a wav file for specific frequency signatures"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<ruby-audio>, [">= 0"])
      s.add_development_dependency(%q<fftw3>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.8.0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<ruby-audio>, [">= 0"])
      s.add_dependency(%q<fftw3>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.8.0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<ruby-audio>, [">= 0"])
    s.add_dependency(%q<fftw3>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

